name: CI for MWAA

on:
  push:
    branches:
      - main

permissions:
  id-token: write    # For OIDC JWT
  contents: read     # To clone repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - name: Clone the repository
        uses: actions/checkout@v4

      # Configure AWS credentials securely using secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Sync Airflow files to S3
      - name: Sync Airflow files to S3
        run: |
          aws s3 sync dags/ s3://your-mwaa-bucket-name/dags/ --follow-symlinks --delete
          aws s3 sync plugins/ s3://your-mwaa-bucket-name/plugins/ --follow-symlinks --delete
          aws s3 sync requirements/ s3://your-mwaa-bucket-name/requirements/ --follow-symlinks --delete
